name: PlatformIO build

on: [push,workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build arduin3/devkitc
        run: |
          pio run -e arduino3
          mv .pio/build/arduino3/firmware.bin devkitc.bin

      - name: Upload devkitc artifacts
        uses: actions/upload-artifact@v3
        #retention-days: 1
        overwrite: true

        with:
          name: devkitc.bin
          path: devkitc.bin

